name = "lean-stochastic"
version = "0.1.0"
defaultTargets = ["lean-stochastic"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"

[[lean_lib]]
name = "LeanStochastic"

[[lean_exe]]
name = "lean-stochastic"
root = "Main"
